version: '3.1'

services:
    docman:
        build: backend
        image: docman
        container_name: docman
        restart: unless-stopped
        volumes:
            - /mnt/docman:/data
        ports:
            - 8123:80
        environment:
            - DOCMAN_DEBUG=TRUE



